apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: ekco
spec:
  # uri: https://raw.githubusercontent.com/replicatedhq/troubleshoot-specs/main/in-cluster/ekco.yaml
  collectors:
    - runPod:
        name: ekco-resources
        namespace: kurl
        podSpec:
          containers:
            - name: inspect-ekco-pods
              image: adamancini/netshoot
              command: ["sh", "-c", "--"]
              args:
                [
                  "kubectl get pod -n kurl --selector app=ekc-operator --field-selector status.phase=Running -o json | jq -r .items[]",
                ]
          restartPolicy: Never
          dnsPolicy: ClusterFirst
          serviceAccount: ekco
  analyzers:
    - deploymentStatus:
        checkName: Check EKCO is operational
        name: ekc-operator
        namespace: kurl
        outcomes:
          - fail:
              when: absent
              message: EKCO is not installed - please add the EKCO component to your kURL spec and re-run the installer script
          - fail:
              when: "< 1"
              message: EKCO does not have any Ready pods
          - pass:
              message: EKCO is installed and running
    - textAnalyze:
        checkName: Check installed EKCO version for critical fixes
        fileName: ekco-resources/ekco-resources.log
        regexGroups: '"image": "replicated/ekco:v(?P<Major>\d+)\.(?P<Minor>\d+)\.(?P<Patch>\d+)"'
        outcomes:
          - warn:
              when: "Minor < 4"
              message: A critical update for cluster certificate rotation has been released in EKCO 0.4.0.  Please upgrade to the latest available version.
          - warn:
              when: "Minor < 19"
              message: A critical fix for registry certificate rotation has been released in EKCO 0.19.3.  Please upgrade to the latest available version.
          - pass:
              when: "Minor > 20"
              message: EKCO version is recent
