apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: ekco
spec:
  uri: https://raw.githubusercontent.com/replicatedhq/troubleshoot-specs/main/in-cluster/ekco.yaml
  collectors:
    - data:
        name: static/ekco.yaml
        data: |-
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: ekc-operator
            namespace: kurl
          spec:
            containers:
              - name: ekc-operator
                image: replicated/ekco:v0.4.1
  analyzers:
    - deploymentStatus:
        checkName: Check EKCO is operational
        name: ekc-operator
        namespace: kurl
        outcomes:
          - fail:
              when: absent
              message: EKCO is not installed - please add the EKCO component to your kURL spec and re-run the installer script
          - fail:
              when: "< 1"
              message: EKCO does not have any ready replicas
          - pass:
              message: EKCO has at least 1 replica
    - textAnalyze:
        checkName: Check installed EKCO version
        fileName: static/ekco.yaml
        regexGroups: 'image: replicated/ekco:v(?P<Major>\d+)\.(?P<Minor>\d+)\.(?P<Patch>\d+)'
        outcomes:
          - warn:
              when: "Minor < 5"
              message: A very important bug fix has been released in EKCO 0.5.0.  Please upgrade to the latest available version.
          - pass:
              message: EKCO is up to date
