apiVersion: v1
kind: Pod
metadata:
  labels:
    run: tmp-shell
  name: tmp-shell
spec:
  containers:
    - image: adamancini/netshoot
      name: tmp-shell
      command: ["/bin/bash", "-c", "--"]
      args: ["while true; do sleep 30; done;"]
  dnsPolicy: ClusterFirst
